[phases.setup]
runtime = "python3.10"

[phases.install]
command = "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[phases.start]
command = ". /opt/venv/bin/activate && python run.py"
